const slides: Slide[] = [
  {
    productId: "ergo-aminoshot", 
    image: "https://rjsmqpneamauasuoqzct.supabase.co/storage/v1/object/public/review-photos//7d6b3f9d-61aa-4dd2-baee-3d15bbd2327f.png",
    eyebrow: "300g Intra-Workout Amino",
    title: "Built For Lean Muscle",
    subtitle: "Juicy Fruit Bubblegum • 300g intra-workout amino.",
    cta: "Shop AminoShot",
    bg: "bg-gradient-to-br from-[#eaf1ff] via-[#f6f9ff] to-white",
    text: "text-[#0a1b3d]",
    accent: "bg-[#1d4ed8] hover:bg-[#1e40af] text-white",
  },
  {
    productId: "Super Whey",
    image: "https://rjsmqpneamauasuoqzct.supabase.co/storage/v1/object/public/review-photos//WhatsApp Image 2026-06-05 at 3.24.31 PM.jpeg",
    eyebrow: "HIGH VOLTAGE",
    title: "Train At Full Throttle",
    subtitle: "Our premium cold-processed whey protein is designed for rapid absorption and clean muscle synthesis.",
    cta: "Shop Super Whey",
    bg: "bg-gradient-to-br from-[#0b1220] via-[#0d1a33] to-[#0a0f1f]",
    text: "text-white",
    accent: "!bg-[#1d4ed8] hover:!bg-[#1e40af] !text-white",
  },
  {
    productId: "ergo-lean-shot",
    image: "https://rjsmqpneamauasuoqzct.supabase.co/storage/v1/object/public/review-photos//fa87092f-ed7a-4f2a-a943-2d5acf883b09.png",
    eyebrow: "THERMOGENIC EDGE",
    title: "Burn Cleaner. Move Sharper.",
    subtitle: "Lean Shot fuels fat metabolism with sustained energy and crystal focus.",
    cta: "Shop Lean Shot",
    bg: "bg-gradient-to-br from-white via-[#f1f5ff] to-[#dbe7ff]",
    text: "text-[#0a1b3d]",
    accent: "bg-[#1d4ed8] hover:bg-[#1e40af] text-white",
  },
];